export default function () {
    return [
        { id: 1, skill: "React", tag: "JavaScript" },
        { id: 2, skill: "Node", tag: "JavaScript" },
        { id: 3, skill: "Angular", tag: "JavaScript" },
        { id: 4, skill: "jQuery", tag: "JavaScript" },
        { id: 5, skill: "Webpack", tag: "JavaScript" },
        { id: 6, skill: "Jasmine", tag: "JavaScript" },
        { id: 7, skill: "Mocha", tag: "JavaScript" },
        { id: 8, skill: "HTML(5)", tag: "Web" },
        { id: 9, skill: "CSS(3)", tag: "Web" },
        { id: 10, skill: "SASS", tag: "Web" },
        { id: 11, skill: "Bootstrap", tag: "Web" },
        { id: 12, skill: "SVG", tag: "Web" },
        { id: 13, skill: "OpenGL", tag: "Web" },
        { id: 14, skill: "Hack", tag: "PHP" },
        { id: 15, skill: "HHVM", tag: "PHP" },
        { id: 16, skill: "Laravel", tag: "PHP" },
        { id: 17, skill: "Symphony", tag: "PHP" },
        { id: 18, skill: "Photoshop", tag: "Design" },
        { id: 19, skill: "Sketch", tag: "Design" },
        { id: 20, skill: "Illustrator", tag: "Design" },
        { id: 21, skill: "Apache", tag: "Sundry" },
        { id: 22, skill: "NGINX", tag: "Sundry" },
        { id: 23, skill: "GIT", tag: "Sundry" },
        { id: 24, skill: "C++", tag: "Sundry" },
        { id: 25, skill: "Java", tag: "Sundry" },
        { id: 26, skill: "Bash", tag: "Sundry" },
        { id: 27, skill: "NPM", tag: "JavaScript" }
    ];
};